### ISSUE TITLE
Have a 'sign out' button, that, well, signs you out.

### ISSUE THREAD

**Issue by ja-besse** [pebble-dev/rebble-auth-py#8]
Since people sometimes forget with which (type of) account they signed in (and maybe opted in for the paid plan), they can get confused when accidentally signing in with a different account.

Since signing out currently is only possible by removing cookies (which, on some mobile browsers / operating systems, is not easy and might only be doable by deleting ALL cookies for ALL sites), it would be helpful to have a sign out button, that removes or invalidates the authentication cookies.

This would also remove the need for the corresponding issue listed on rebble.io/howto.

**Comment by jwise** [comment]
Branch jwise/show-yourself-coward-i-will-never-log-off.  Probably should also add to the account page info on what identity provider you logged in with, too.

**Comment by jwise** [comment]
REJOICE: Both of those are live and in production!  I only broke absolutely everything once, and I figured it out like 45 seconds later.  So we're definitely still above 99.99% uptime, which is good enough for me.  You can see them at: https://auth.rebble.io/account/
